"""Added Cookie model

Revision ID: 6d212e6c24ff
Revises: 1ecb9ef4a5eb
Create Date: 2018-06-12 10:34:13.048751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '6d212e6c24ff'
down_revision = '1ecb9ef4a5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookies',
    sa.Column('cookie_id', sa.Integer(), nullable=False),
    sa.Column('cookie_name', sa.String(length=50), nullable=True),
    sa.Column('cookie_recipe_url', sa.String(length=255), nullable=True),
    sa.Column('cookie_sku', sa.String(length=55), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('cookie_id'),
    schema='practice'
    )
    op.create_index(op.f('ix_practice_cookies_cookie_name'), 'cookies', ['cookie_name'], unique=False, schema='practice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_cookies_cookie_name'), table_name='cookies', schema='practice')
    op.drop_table('cookies', schema='practice')
    # ### end Alembic commands ###
